# Lab | Data Structuring and Combining Data

## Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

## Loading the cleaned df from the previous exercise:

In [10]:
import pandas as pd

df_1 = pd.read_csv("/Users/lee/Documents/GitHub/lab-dw-data-cleaning-and-formatting/cleaned_data.csv")
df_1.head(10)

,Customer id,State,Gender,Education,Customer_Lifetime_Value,Income,Monthly_Premium_Auto,Number_of_Open_Complaints,Policy_Type,Vehicle_Class,Total_Claim_Amount
0,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,NaN,Personal Auto,Four-Door Car,1131.464935
1,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,NaN,Personal Auto,Two-Door Car,566.472247
2,WW63253,California,M,Bachelor,764586.18,0.0,106.0,NaN,Corporate Auto,SUV,529.881344
3,GA49547,Washington,M,High School or Below,536307.65,36357.0,68.0,NaN,Personal Auto,Four-Door Car,17.269323
4,OC83172,Oregon,F,Bachelor,825629.78,62902.0,69.0,NaN,Personal Auto,Two-Door Car,159.383042
5,XZ87318,Oregon,F,College,538089.86,55350.0,67.0,NaN,Corporate Auto,Four-Door Car,321.600000
6,CF85061,Arizona,M,Master,721610.03,0.0,101.0,NaN,Corporate Auto,Four-Door Car,363.029680
7,DY87989,Oregon,M,Bachelor,2412750.40,14072.0,71.0,NaN,Corporate Auto,Four-Door Car,511.200000
8,BQ94931,Oregon,F,College,738817.81,28812.0,93.0,NaN,Special Auto,Four-Door Car,425.527834
9,SX51350,California,M,College,473899.20,0.0,67.0,NaN,Personal Auto,Four-Door Car,482.400000

## Loading the new dataframes for this exercise:

In [5]:
df_2 = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv")
df_2.head(10)

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Total Claim Amount,Policy Type,Vehicle Class
0,GS98873,Arizona,F,Bachelor,323912.47%,16061,88,1/0/00,633.600000,Personal Auto,Four-Door Car
1,CW49887,California,F,Master,462680.11%,79487,114,1/0/00,547.200000,Special Auto,SUV
2,MY31220,California,F,College,899704.02%,54230,112,1/0/00,537.600000,Personal Auto,Two-Door Car
3,UH35128,Oregon,F,College,2580706.30%,71210,214,1/1/00,1027.200000,Personal Auto,Luxury Car
4,WH52799,Arizona,F,College,380812.21%,94903,94,1/0/00,451.200000,Corporate Auto,Two-Door Car
5,WL99637,Arizona,M,Bachelor,761413.80%,27293,96,1/0/00,469.030907,Personal Auto,Two-Door Car
6,UC84059,California,F,Master,689845.53%,70950,171,1/0/00,565.929394,Personal Auto,Sports Car
7,HW62747,Oregon,M,College,229837.92%,0,63,1/0/00,302.400000,Corporate Auto,Four-Door Car
8,BH11344,Oregon,F,Doctor,280669.61%,37009,71,1/0/00,145.673348,Corporate Auto,Two-Door Car
9,TX28465,Nevada,M,College,520611.82%,52629,65,1/0/00,136.684141,Personal Auto,Four-Door Car

In [6]:
df_3 = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv")
df_3.head(10)

,Customer,State,Customer Lifetime Value,Education,Gender,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Total Claim Amount,Vehicle Class
0,SA25987,Washington,3479.137523,High School or Below,M,0,104,0,Personal Auto,499.200000,Two-Door Car
1,TB86706,Arizona,2502.637401,Master,M,0,66,0,Personal Auto,3.468912,Two-Door Car
2,ZL73902,Nevada,3265.156348,Bachelor,F,25820,82,0,Personal Auto,393.600000,Four-Door Car
3,KX23516,California,4455.843406,High School or Below,F,0,121,0,Personal Auto,699.615192,SUV
4,FN77294,California,7704.958480,High School or Below,M,30366,101,2,Personal Auto,484.800000,SUV
5,VI78454,Arizona,2750.705045,College,M,51789,70,0,Personal Auto,336.000000,Four-Door Car
6,FP59138,Oregon,13024.130120,Master,M,0,125,0,Personal Auto,900.000000,SUV
7,XN62489,Oregon,2538.626320,Bachelor,M,18608,71,0,Corporate Auto,340.800000,Four-Door Car
8,GP66031,California,2585.955652,College,F,83758,64,0,Corporate Auto,106.591949,Two-Door Car
9,IX68587,Nevada,5096.673223,Master,F,22886,65,0,Personal Auto,312.000000,Four-Door Car

## Cleaning the new dataframes:

In [11]:
df_2.columns = df_2.columns.str.replace(" ", "_")
df_3.columns = df_3.columns.str.replace(" ", "_")

In [12]:
df_2= df_2.rename(columns={"Customer": "Customer id", "ST": "State", "GENDER": "Gender"})
df_3= df_3.rename(columns={"Customer": "Customer id"})

In [13]:
df_2["Gender"].value_counts()

Gender
F         527
M         461
female      2
Male        1
Name: count, dtype: int64

In [15]:
df_2["Gender"] = df_2["Gender"].replace({"female": "F", "Male": "M"})

In [16]:
df_2["Gender"].value_counts()

Gender
F    529
M    462
Name: count, dtype: int64

In [14]:
df_3["Gender"].value_counts()

Gender
F    3576
M    3494
Name: count, dtype: int64

In [17]:
df_2["State"].value_counts()

State
Oregon        303
California    277
Arizona       142
Nevada        125
Washington    100
AZ             49
Name: count, dtype: int64

In [20]:
df_2["State"] = df_2["State"].replace({"AZ": "Arizona"})

In [21]:
df_2["State"].value_counts()

State
Oregon        303
California    277
Arizona       191
Nevada        125
Washington    100
Name: count, dtype: int64

In [18]:
df_3["State"].value_counts()

State
California    2544
Oregon        1978
Arizona       1302
Nevada         659
Washington     587
Name: count, dtype: int64

In [22]:
df_2["Education"].value_counts()

Education
College                 311
High School or Below    290
Bachelor                243
Master                   86
Doctor                   49
Bachelors                17
Name: count, dtype: int64

In [23]:
df_2["Education"] = df_2["Education"].replace({"Bachelors": "Bachelor"})

In [24]:
df_2["Education"].value_counts()

Education
College                 311
High School or Below    290
Bachelor                260
Master                   86
Doctor                   49
Name: count, dtype: int64

In [25]:
df_3["Education"].value_counts()

Education
Bachelor                2152
College                 2058
High School or Below    2030
Master                   572
Doctor                   258
Name: count, dtype: int64

In [26]:
df_2["Customer_Lifetime_Value"].value_counts()

Customer_Lifetime_Value
552821.28%     4
600521.48%     3
538949.95%     3
1203662.05%    3
871704.98%     3
              ..
728503.10%     1
1765196.34%    1
1702989.34%    1
403931.50%     1
399258.39%     1
Name: count, Length: 950, dtype: int64

In [28]:
df_2["Customer_Lifetime_Value"] = df_2["Customer_Lifetime_Value"].str.rstrip("%")

In [27]:
df_3["Customer_Lifetime_Value"].value_counts()

Customer_Lifetime_Value
2647.519741     6
2659.705650     6
4686.469674     6
4270.034394     6
13727.799720    6
               ..
11281.524510    1
8759.592518     1
4928.001408     1
4896.261605     1
2611.836866     1
Name: count, Length: 6288, dtype: int64

In [29]:
df_2["Vehicle_Class"].value_counts()

Vehicle_Class
Four-Door Car    519
Two-Door Car     211
SUV              174
Sports Car        55
Luxury SUV        21
Luxury Car        16
Name: count, dtype: int64

In [30]:
df_2["Vehicle_Class"] = df_2["Vehicle_Class"].replace({"Sports Car": "Luxury", "Luxury SUV": "Luxury", "Luxury Car": "Luxury"})

In [31]:
df_2["Vehicle_Class"].value_counts()

Vehicle_Class
Four-Door Car    519
Two-Door Car     211
SUV              174
Luxury            92
Name: count, dtype: int64

In [32]:
df_3["Vehicle_Class"].value_counts()

Vehicle_Class
Four-Door Car    3546
Two-Door Car     1480
SUV              1401
Sports Car        371
Luxury SUV        141
Luxury Car        131
Name: count, dtype: int64

In [33]:
df_3["Vehicle_Class"] = df_3["Vehicle_Class"].replace({"Sports Car": "Luxury", "Luxury SUV": "Luxury", "Luxury Car": "Luxury"})

In [34]:
df_3["Vehicle_Class"].value_counts()

Vehicle_Class
Four-Door Car    3546
Two-Door Car     1480
SUV              1401
Luxury            643
Name: count, dtype: int64

In [38]:
df_2["Number_of_Open_Complaints"] = df_2["Number_of_Open_Complaints"].str.split("/").str[1]

## Loading the cleaned dataframes

In [35]:
df_1.head()

,Customer id,State,Gender,Education,Customer_Lifetime_Value,Income,Monthly_Premium_Auto,Number_of_Open_Complaints,Policy_Type,Vehicle_Class,Total_Claim_Amount
0,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,NaN,Personal Auto,Four-Door Car,1131.464935
1,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,NaN,Personal Auto,Two-Door Car,566.472247
2,WW63253,California,M,Bachelor,764586.18,0.0,106.0,NaN,Corporate Auto,SUV,529.881344
3,GA49547,Washington,M,High School or Below,536307.65,36357.0,68.0,NaN,Personal Auto,Four-Door Car,17.269323
4,OC83172,Oregon,F,Bachelor,825629.78,62902.0,69.0,NaN,Personal Auto,Two-Door Car,159.383042

In [39]:
df_2.head()

,Customer id,State,Gender,Education,Customer_Lifetime_Value,Income,Monthly_Premium_Auto,Number_of_Open_Complaints,Total_Claim_Amount,Policy_Type,Vehicle_Class
0,GS98873,Arizona,F,Bachelor,323912.47,16061,88,0,633.6,Personal Auto,Four-Door Car
1,CW49887,California,F,Master,462680.11,79487,114,0,547.2,Special Auto,SUV
2,MY31220,California,F,College,899704.02,54230,112,0,537.6,Personal Auto,Two-Door Car
3,UH35128,Oregon,F,College,2580706.30,71210,214,1,1027.2,Personal Auto,Luxury
4,WH52799,Arizona,F,College,380812.21,94903,94,0,451.2,Corporate Auto,Two-Door Car

In [37]:
df_3.head()

,Customer id,State,Customer_Lifetime_Value,Education,Gender,Income,Monthly_Premium_Auto,Number_of_Open_Complaints,Policy_Type,Total_Claim_Amount,Vehicle_Class
0,SA25987,Washington,3479.137523,High School or Below,M,0,104,0,Personal Auto,499.200000,Two-Door Car
1,TB86706,Arizona,2502.637401,Master,M,0,66,0,Personal Auto,3.468912,Two-Door Car
2,ZL73902,Nevada,3265.156348,Bachelor,F,25820,82,0,Personal Auto,393.600000,Four-Door Car
3,KX23516,California,4455.843406,High School or Below,F,0,121,0,Personal Auto,699.615192,SUV
4,FN77294,California,7704.958480,High School or Below,M,30366,101,2,Personal Auto,484.800000,SUV

## Concatenating the datasets

In [40]:
df_all = pd.concat([df_1, df_2, df_3], ignore_index=True)

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [46]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv")
df.head()

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,A,1

In [67]:
df.columns

Index(['customer', 'state', 'customer_lifetime_value', 'response', 'coverage',
       'education', 'effective_to_date', 'employmentstatus', 'gender',
       'income', 'location_code', 'marital_status', 'monthly_premium_auto',
       'months_since_last_claim', 'months_since_policy_inception',
       'number_of_open_complaints', 'number_of_policies', 'policy_type',
       'policy', 'renew_offer_type', 'sales_channel', 'total_claim_amount',
       'vehicle_class', 'vehicle_size', 'vehicle_type', 'month'],
      dtype='object')

## Cleaning the Dataset

In [48]:
df = df.drop(columns=["unnamed:_0"])

In [60]:
df["vehicle_class"].value_counts()

vehicle_class
Four-Door Car    5834
Two-Door Car     2118
SUV              2012
Sports Car        550
Luxury SUV        208
Luxury Car        188
Name: count, dtype: int64

In [63]:
df["vehicle_class"] = df["vehicle_class"].replace({"Sports Car": "Luxury Car","Luxury SUV": "Luxury Car"})

In [65]:
df["vehicle_size"].value_counts()

vehicle_size
Medsize    7873
Small      1966
Large      1071
Name: count, dtype: int64

In [66]:
df["vehicle_size"] = df["vehicle_size"].replace({"Medsize": "Medium"})

## Exploration and Analysis

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

In [ ]:
pivot_1 = df.pivot_table(
    values = "monthly_premium_auto", #what should be calculated (as sum, count)
    index = "sales_channel", #with reference to which parameter
    aggfunc = "sum" #since total revenue is asked, sum is used
).round(2)

pivot_1

               monthly_premium_auto
sales_channel
Agent                        386335
Branch                       280953
Call Center                  197970
Web                          151511

Insights:
- Marketing through 'agents' has fetched the most revenue. This could be an indicator that personal contact works the best with the customers.
- Call Center is also targeted to contact customers regarding the products, but it is only the third most revenue generating. This could mean that the 'call center' personnel could use some training from the 'agents' on how to bring more customers, how to market different products successfully.
- Web channel is the least revenue generating. So paid marketing team's efforts should be reformed and mesaured. Or it could mean that most of our customers / target customers do not use web enough for us to attract them through the channel, i.e., could be seniors / not so tech savvy group.

In [ ]:
pivot_2 = df.pivot_table(
    values = "customer_lifetime_value", #what should be calculated (as sum, count)
    index = "gender", #with reference to which parameter
    aggfunc = "mean" #since average CLV is asked, mean is used
).round(2)
pivot_2

        customer_lifetime_value
gender
F                       8071.11
M                       7963.04

In [87]:
df["gender"].value_counts()

gender
F    5573
M    5337
Name: count, dtype: int64

Insights:
- Female customers have an avg CLV of 8k, which is more or less equal to that of the male customer CLV. It could mean that targeting a single gender for marketing would not make much difference. This is also due to the fact that the number of male and female customers are almost the same. 
- Since they both generate around the same CLV, the pricing team may also use this data to price their policies /premiums similarly.

In [ ]:
pivot_2 = df.pivot_table(
    values = "customer_lifetime_value", #what should be calculated (as sum, count)
    index = "education", #with reference to which parameter
    aggfunc = "mean" #since average CLV is asked, mean is used
).round(2)
pivot_2

                      customer_lifetime_value
education
Bachelor                              7792.27
College                               7900.07
Doctor                                7372.03
High School or Below                  8415.29
Master                                8162.52

In [88]:
df["education"].value_counts()

education
Bachelor                3272
College                 3204
High School or Below    3146
Master                   887
Doctor                   401
Name: count, dtype: int64

Insights:
- Customers who have an education of high school or below have the highest CLV, followed by Masters holders.
- The least CLV holders are the customers with doctorates. 
- Does a higher education level mean they know / learn how to use their insurance policies / companies to their maximum benefit? Since Masters holders also have a relatively low CLV, this might not hold good for this theory overall, but interesting perspective to look into.

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [89]:
df["number_of_open_complaints"].value_counts()

number_of_open_complaints
0.000000    8160
1.000000    1145
0.384256     633
2.000000     414
3.000000     324
4.000000     166
5.000000      68
Name: count, dtype: int64

In [97]:
complaints = (
    df.groupby(["policy_type", "month"])["number_of_open_complaints"]
    .sum()
    .reset_index()
    .round()
)

In [98]:
print(complaints) #display the above as a long format table

      policy_type  month  number_of_open_complaints
0  Corporate Auto      1                      443.0
1  Corporate Auto      2                      385.0
2   Personal Auto      1                     1728.0
3   Personal Auto      2                     1454.0
4    Special Auto      1                       87.0
5    Special Auto      2                       95.0

In [96]:
pivot = df.pivot_table(
    values = "number_of_open_complaints",
    index = "month",
    aggfunc= "sum"
).round()
pivot

       number_of_open_complaints
month
1                         2258.0
2                         1934.0

Insights:
- The month January and February saw the most number of open complaints. 
- Month January saw the most number of open complaints, followed by February. 
- This could mean that there is an overlag from the staff due to December holidays, so complaints were carried forward to the following two months for actioning.
- It could also mean that there are more customer complaints at the beginning of the year because customers realise and focus on the policies / investments they hold during that time and want to get their issues resolved.